
const movies = [
    {
      id: 1,
      title: "肖申克的救赎",
      englishTitle: "The Shawshank Redemption",
      year: 1994,
      director: "弗兰克·德拉邦特",
      genres: ["剧情", "犯罪"],
      rating: 9.6,
      description: "两个被监禁的男人在数年间找到慰藉与救赎，通过共同的爱好和小小的仁慈行为。",
      keywords: ["监狱", "友情", "希望", "自由", "正义"],
      countries: ["美国"],
      cast: ["蒂姆·罗宾斯", "摩根·弗里曼"],
      searchTerms: "肖申克的救赎 肖申克 救赎 弗兰克·德拉邦特 剧情 犯罪 1994"
    },
    {
      id: 2,
      title: "教父",
      englishTitle: "The Godfather",
      year: 1972,
      director: "弗朗西斯·福特·科波拉",
      genres: ["剧情", "犯罪"],
      rating: 9.3,
      description: "一个有组织犯罪家族的老化patriarch将控制权移交给他不情愿的儿子。",
      keywords: ["黑手党", "家族", "权力", "忠诚", "复仇"],
      countries: ["美国"],
      cast: ["马龙·白兰度", "阿尔·帕西诺"],
      searchTerms: "教父 弗朗西斯·福特·科波拉 剧情 犯罪 1972"
    },
    {
      id: 3,
      title: "蝙蝠侠：黑暗骑士",
      englishTitle: "The Dark Knight",
      year: 2008,
      director: "克里斯托弗·诺兰",
      genres: ["动作", "犯罪", "剧情"],
      rating: 9.1,
      description: "当小丑出现并引发混乱时，蝙蝠侠必须接受一场针对他所保护的城市的最大心理和身体考验。",
      keywords: ["超级英雄", "犯罪", "正义", "混乱", "道德"],
      countries: ["美国", "英国"],
      cast: ["克里斯蒂安·贝尔", "希斯·莱杰"],
      searchTerms: "蝙蝠侠 黑暗骑士 克里斯托弗·诺兰 动作 犯罪 剧情 2008"
    },
    {
      id: 4,
      title: "星际穿越",
      englishTitle: "Interstellar",
      year: 2014,
      director: "克里斯托弗·诺兰",
      genres: ["冒险", "剧情", "科幻"],
      rating: 9.2,
      description: "一组探险家通过新发现的虫洞进行星际旅行，以寻找人类的新家园。",
      keywords: ["太空", "时间", "爱", "科学", "生存"],
      countries: ["美国", "英国", "加拿大"],
      cast: ["马修·麦康纳", "安妮·海瑟薇"],
      searchTerms: "星际穿越 克里斯托弗·诺兰 冒险 剧情 科幻 2014"
    },
    {
      id: 5,
      title: "盗梦空间",
      englishTitle: "Inception",
      year: 2010,
      director: "克里斯托弗·诺兰",
      genres: ["动作", "冒险", "科幻"],
      rating: 9.3,
      description: "一个窃取企业秘密的小偷被给予了植入另一个人想法的任务。",
      keywords: ["梦境", "潜意识", "现实", "记忆", "想法"],
      countries: ["美国", "英国"],
      cast: ["莱昂纳多·迪卡普里奥", "约瑟夫·高登-莱维特"],
      searchTerms: "盗梦空间 克里斯托弗·诺兰 动作 冒险 科幻 2010"
    },
    {
      id: 6,
      title: "泰坦尼克号",
      englishTitle: "Titanic",
      year: 1997,
      director: "詹姆斯·卡梅隆",
      genres: ["剧情", "爱情"],
      rating: 9.2,
      description: "一个贫穷的艺术家和一个富有的女子在注定沉没的R.M.S. Titanic的处女航上相爱。",
      keywords: ["爱情", "灾难", "阶级", "牺牲", "命运"],
      countries: ["美国"],
      cast: ["莱昂纳多·迪卡普里奥", "凯特·温斯莱特"],
      searchTerms: "泰坦尼克号 詹姆斯·卡梅隆 剧情 爱情 1997"
    },
    {
      id: 7,
      title: "寻梦环游记",
      englishTitle: "Coco",
      year: 2017,
      director: "李·昂克里奇",
      genres: ["动画", "冒险", "家庭"],
      rating: 9.0,
      description: "热爱音乐的米格尔误入了五彩斑斓的'亡灵之地'，开始了一段不可思议的奇幻旅程。",
      keywords: ["家庭", "文化", "音乐", "记忆", "传统"],
      countries: ["美国"],
      cast: ["安东尼·冈萨雷斯", "盖尔·加西亚·贝纳尔"],
      searchTerms: "寻梦环游记 李·昂克里奇 动画 冒险 家庭 2017"
    },
    {
      id: 8,
      title: "阿甘正传",
      englishTitle: "Forrest Gump",
      year: 1994,
      director: "罗伯特·泽米吉斯",
      genres: ["剧情", "爱情"],
      rating: 9.4,
      description: "智力障碍的阿甘意外地成为美国历史上几个决定性时刻的关键人物。",
      keywords: ["人生", "爱情", "历史", "命运", "坚持"],
      countries: ["美国"],
      cast: ["汤姆·汉克斯", "罗宾·怀特"],
      searchTerms: "阿甘正传 罗伯特·泽米吉斯 剧情 爱情 1994"
    },
    {
      id: 9,
      title: "千与千寻",
      englishTitle: "Spirited Away",
      year: 2001,
      director: "宫崎骏",
      genres: ["动画", "冒险", "家庭"],
      rating: 9.3,
      description: "小女孩千寻在一个奇怪的城镇迷路后，她的父母变成了猪，她必须工作以找到回家的路。",
      keywords: ["成长", "勇气", "精神世界", "自我发现", "友情"],
      countries: ["日本"],
      cast: ["柊瑠美", "入野自由"],
      searchTerms: "千与千寻 宫崎骏 动画 冒险 家庭 2001"
    },
    {
      id: 10,
      title: "复仇者联盟：终局之战",
      englishTitle: "Avengers: Endgame",
      year: 2019,
      director: "安东尼·罗素, 乔·罗素",
      genres: ["动作", "冒险", "科幻"],
      rating: 8.5,
      description: "复仇者联盟对抗灭霸，试图恢复灭霸消灭的宇宙一半生命。",
      keywords: ["超级英雄", "团队", "牺牲", "时间旅行", "最终决战"],
      countries: ["美国"],
      cast: ["小罗伯特·唐尼", "克里斯·埃文斯"],
      searchTerms: "复仇者联盟 终局之战 安东尼·罗素 乔·罗素 动作 冒险 科幻 2019"
    },
    {
      id: 11,
      title: "楚门的世界",
      englishTitle: "The Truman Show",
      year: 1998,
      director: "彼得·威尔",
      genres: ["剧情", "科幻"],
      rating: 9.0,
      description: "一个保险推销员逐渐发现自己整个生活都是一个为全球观众制作的电视节目。",
      keywords: ["现实秀", "自由", "欺骗", "媒体", "觉醒"],
      countries: ["美国"],
      cast: ["金·凯瑞", "劳拉·琳妮"],
      searchTerms: "楚门的世界 彼得·威尔 剧情 科幻 1998"
    },
    {
      id: 12,
      title: "流浪地球",
      englishTitle: "The Wandering Earth",
      year: 2019,
      director: "郭帆",
      genres: ["科幻", "冒险", "动作"],
      rating: 8.0,
      description: "当太阳即将毁灭时，人类试图推动地球离开太阳系，寻找新家园。",
      keywords: ["太空", "灾难", "团结", "牺牲", "未来"],
      countries: ["中国"],
      cast: ["吴京", "屈楚萧"],
      searchTerms: "流浪地球 郭帆 科幻 冒险 动作 2019"
    },
    {
      id: 13,
      title: "大话西游之大圣娶亲",
      englishTitle: "A Chinese Odyssey Part Two: Cinderella",
      year: 1995,
      director: "刘镇伟",
      genres: ["喜剧", "爱情", "奇幻"],
      rating: 9.2,
      description: "至尊宝被月光宝盒带回到五百年前，遇见紫霞仙子，并被七个蜘蛛精抓走，后来与紫霞成为了一对。",
      keywords: ["爱情", "孙悟空", "命运", "西游记", "穿越"],
      countries: ["中国香港", "中国"],
      cast: ["周星驰", "朱茵"],
      searchTerms: "大话西游 周星驰 朱茵 喜剧 爱情 奇幻 1995"
    },
    {
      id: 14,
      title: "让子弹飞",
      englishTitle: "Let the Bullets Fly",
      year: 2010,
      director: "姜文",
      genres: ["剧情", "喜剧", "动作"],
      rating: 9.0,
      description: "一伙强盗在动荡的军阀时期劫持了一个县长的火车，为了金钱和权力，他们伪装成县长与当地恶霸展开了一场斗智斗勇的较量。",
      keywords: ["黑色幽默", "权力", "智斗", "民国", "匪徒"],
      countries: ["中国"],
      cast: ["姜文", "葛优", "周润发"],
      searchTerms: "让子弹飞 姜文 剧情 喜剧 动作 2010"
    },
    {
      id: 15,
      title: "功夫",
      englishTitle: "Kung Fu Hustle",
      year: 2004,
      director: "周星驰",
      genres: ["动作", "喜剧", "犯罪"],
      rating: 8.7,
      description: "上海贫民窟的一个小混混想要加入一个凶残的黑帮，但他无意中卷入了与功夫高手的连串冲突。",
      keywords: ["功夫", "黑帮", "喜剧", "动作", "英雄"],
      countries: ["中国香港", "中国"],
      cast: ["周星驰", "元秋", "元华"],
      searchTerms: "功夫 周星驰 动作 喜剧 犯罪 2004"
    },
    {
      id: 16,
      title: "指环王：王者归来",
      englishTitle: "The Lord of the Rings: The Return of the King",
      year: 2003,
      director: "彼得·杰克逊",
      genres: ["冒险", "奇幻", "剧情"],
      rating: 9.2,
      description: "甘道夫和亚拉冈领导世界的人类抵抗索伦的军队，而弗罗多和山姆则接近魔多以销毁至尊魔戒。",
      keywords: ["魔戒", "战争", "友情", "牺牲", "中土世界"],
      countries: ["新西兰", "美国"],
      cast: ["伊利亚·伍德", "维果·莫腾森", "伊恩·麦克莱恩"],
      searchTerms: "指环王 王者归来 彼得·杰克逊 冒险 奇幻 剧情 2003"
    },
    {
      id: 17,
      title: "我不是药神",
      englishTitle: "Dying to Survive",
      year: 2018,
      director: "文牧野",
      genres: ["剧情", "喜剧"],
      rating: 9.0,
      description: "一个保健品店老板偶然卖起了印度仿制药，被病人称为‘药神’，但这也让他面临法律和道德的考验。",
      keywords: ["药品", "生命", "道德", "法律", "真实事件"],
      countries: ["中国"],
      cast: ["徐峥", "王传君", "周一围"],
      searchTerms: "我不是药神 文牧野 徐峥 剧情 喜剧 2018"
    },
    {
      id: 18,
      title: "哈利·波特与魔法石",
      englishTitle: "Harry Potter and the Philosopher's Stone",
      year: 2001,
      director: "克里斯·哥伦布",
      genres: ["冒险", "家庭", "奇幻"],
      rating: 8.9,
      description: "一个被遗弃的男孩在11岁时发现了他的身世，并前往一所魔法学校学习魔法。",
      keywords: ["魔法", "友谊", "成长", "霍格沃茨", "魔法石"],
      countries: ["英国", "美国"],
      cast: ["丹尼尔·雷德克里夫", "艾玛·沃森", "鲁伯特·格林特"],
      searchTerms: "哈利·波特 魔法石 克里斯·哥伦布 冒险 家庭 奇幻 2001"
    },
    {
      id: 19,
      title: "这个杀手不太冷",
      englishTitle: "Léon: The Professional",
      year: 1994,
      director: "吕克·贝松",
      genres: ["动作", "犯罪", "剧情"],
      rating: 9.4,
      description: "一个专业杀手收留了一个12岁的女孩，女孩的家人被腐败的警察杀害了。",
      keywords: ["杀手", "救赎", "复仇", "成长", "爱"],
      countries: ["法国", "美国"],
      cast: ["让·雷诺", "娜塔莉·波特曼", "加里·奥德曼"],
      searchTerms: "这个杀手不太冷 吕克·贝松 动作 犯罪 剧情 1994"
    },
    {
      id: 20,
      title: "你的名字。",
      englishTitle: "Your Name.",
      year: 2016,
      director: "新海诚",
      genres: ["动画", "剧情", "爱情"],
      rating: 9.0,
      description: "两个陌生的高中生发现他们偶尔会互相交换身体，并开始通过留言沟通建立联系。",
      keywords: ["身体互换", "爱情", "灾难", "命运", "时间"],
      countries: ["日本"],
      cast: ["上白石萌音", "神木隆之介"],
      searchTerms: "你的名字 新海诚 动画 剧情 爱情 2016"
    },
    {
      id: 21,
      title: "天空之城",
      englishTitle: "Castle in the Sky",
      year: 1986,
      director: "宫崎骏",
      genres: ["动画", "冒险", "奇幻"],
      rating: 9.1,
      description: "一个神秘的水晶引领一个男孩和一个女孩踏上寻找传说中天空之城的冒险。",
      keywords: ["飞行", "遗迹", "冒险", "环保", "科技"],
      countries: ["日本"],
      cast: ["田中真弓", "横泽启子"],
      searchTerms: "天空之城 宫崎骏 动画 冒险 奇幻 1986"
    },
    {
      id: 22,
      title: "白蛇2：青蛇劫起",
      englishTitle: "White Snake 2: The Tribulation of the Green Snake",
      year: 2021,
      director: "黄家康, 赵霁",
      genres: ["动画", "奇幻", "冒险"],
      rating: 8.0,
      description: "法海大战东海水族，青蛇为救姐姐白蛇被法海打入了深渊。她在苦境中不断成长，学会面对自己。",
      keywords: ["修行", "成长", "神话", "冒险", "法术"],
      countries: ["中国"],
      cast: ["唐小喜", "张喆", "杨天翔"],
      searchTerms: "白蛇2 青蛇劫起 动画 奇幻 冒险 2021"
    },
    {
      id: 23,
      title: "黑客帝国",
      englishTitle: "The Matrix",
      year: 1999,
      director: "莉莉·沃卓斯基, 拉娜·沃卓斯基",
      genres: ["动作", "科幻"],
      rating: 9.0,
      description: "一个电脑黑客了解到他所感知的现实其实是由称为‘矩阵’的复杂计算机系统创造的。",
      keywords: ["虚拟现实", "人工智能", "反乌托邦", "哲学", "革命"],
      countries: ["美国", "澳大利亚"],
      cast: ["基努·里维斯", "劳伦斯·菲什伯恩", "凯莉-安·莫斯"],
      searchTerms: "黑客帝国 矩阵 动作 科幻 1999"
    },
    {
      id: 24,
      title: "釜山行",
      englishTitle: "Train to Busan",
      year: 2016,
      director: "延尚昊",
      genres: ["动作", "惊悚", "恐怖"],
      rating: 8.5,
      description: "当一场僵尸病毒爆发时，一群乘客困在了从首尔开往釜山的高速列车上。",
      keywords: ["僵尸", "生存", "牺牲", "父女", "灾难"],
      countries: ["韩国"],
      cast: ["孔侑", "郑有美", "马东锡"],
      searchTerms: "釜山行 延尚昊 动作 惊悚 恐怖 2016"
    },
    {
      id: 25,
      title: "无间道",
      englishTitle: "Infernal Affairs",
      year: 2002,
      director: "刘伟强, 麦兆辉",
      genres: ["犯罪", "剧情", "惊悚"],
      rating: 9.2,
      description: "警方安插卧底进入黑社会，同时黑社会也派卧底混入警署，双方都急于找出对方的卧底。",
      keywords: ["卧底", "身份", "忠诚", "警察", "黑帮"],
      countries: ["中国香港"],
      cast: ["梁朝伟", "刘德华", "黄秋生"],
      searchTerms: "无间道 刘伟强 麦兆辉 犯罪 剧情 惊悚 2002"
    },
    {
      id: 26,
      title: "头号玩家",
      englishTitle: "Ready Player One",
      year: 2018,
      director: "史蒂文·斯皮尔伯格",
      genres: ["动作", "冒险", "科幻"],
      rating: 8.7,
      description: "在2045年，人们可以逃离现实世界，进入虚拟世界OASIS。一个年轻玩家发现了创始人留下的彩蛋，开始了一场冒险。",
      keywords: ["虚拟世界", "彩蛋", "游戏", "80年代", "竞赛"],
      countries: ["美国"],
      cast: ["泰伊·谢里丹", "奥利维亚·库克", "本·门德尔森"],
      searchTerms: "头号玩家 史蒂文·斯皮尔伯格 动作 冒险 科幻 2018"
    },
    {
      id: 27,
      title: "大鱼",
      englishTitle: "Big Fish",
      year: 2003,
      director: "蒂姆·波顿",
      genres: ["冒险", "剧情", "奇幻"],
      rating: 8.8,
      description: "一个年轻人试图了解他那讲故事的父亲的真实生活，同时也重建了他父亲过去的旅程。",
      keywords: ["父子", "故事", "生命", "爱情", "想象"],
      countries: ["美国"],
      cast: ["伊万·麦克格雷格", "阿尔伯特·芬尼", "比利·克鲁德普"],
      searchTerms: "大鱼 蒂姆·波顿 冒险 剧情 奇幻 2003"
    },
    {
      id: 28,
      title: "狮子王",
      englishTitle: "The Lion King",
      year: 1994,
      director: "罗杰·阿勒斯, 罗伯·明可夫",
      genres: ["动画", "冒险", "剧情"],
      rating: 9.0,
      description: "小狮子王辛巴在父亲的死亡后逃离家园，成年后返回夺回王位。",
      keywords: ["成长", "责任", "王国", "复仇", "家庭"],
      countries: ["美国"],
      cast: ["马修·布罗德里克", "詹姆斯·厄尔·琼斯", "杰瑞米·艾恩斯"],
      searchTerms: "狮子王 动画 冒险 剧情 1994"
    },
    {
      id: 29,
      title: "海上钢琴师",
      englishTitle: "The Legend of 1900",
      year: 1998,
      director: "朱塞佩·托纳多雷",
      genres: ["剧情", "音乐", "爱情"],
      rating: 9.2,
      description: "一个出生并终生生活在邮轮上的天才钢琴家的传奇故事。",
      keywords: ["钢琴", "船", "音乐", "天才", "自由"],
      countries: ["意大利"],
      cast: ["蒂姆·罗斯", "普路特·泰勒·文斯", "比尔·努恩"],
      searchTerms: "海上钢琴师 朱塞佩·托纳多雷 剧情 音乐 爱情 1998"
    },
    {
      id: 30,
      title: "疯狂动物城",
      englishTitle: "Zootopia",
      year: 2016,
      director: "拜伦·霍华德, 瑞奇·摩尔",
      genres: ["动画", "冒险", "喜剧"],
      rating: 9.1,
      description: "在一个由各种动物组成的现代化城市中，一位新晋警官兔子朱迪与一只狡猾的狐狸尼克合作，共同破获一个神秘案件。",
      keywords: ["动物", "社会", "歧视", "友情", "破案"],
      countries: ["美国"],
      cast: ["金妮弗·古德温", "杰森·贝特曼", "伊德里斯·艾尔巴"],
      searchTerms: "疯狂动物城 动画 冒险 喜剧 2016"
    },
    {
      id: 31,
      title: "辛德勒的名单",
      englishTitle: "Schindler's List",
      year: 1993,
      director: "史蒂文·斯皮尔伯格",
      genres: ["传记", "剧情", "历史"],
      rating: 9.0,
      description: "在二战期间的波兰，一位德国商人奥斯卡·辛德勒通过雇佣犹太工人，拯救了一千多名犹太人的生命。",
      keywords: ["二战", "犹太人", "大屠杀", "拯救", "人性"],
      countries: ["美国"],
      cast: ["连姆·尼森", "本·金斯利", "拉尔夫·费因斯"],
      searchTerms: "辛德勒的名单 史蒂文·斯皮尔伯格 传记 剧情 历史 1993"
    },
    {
      id: 32,
      title: "美丽人生",
      englishTitle: "Life Is Beautiful",
      year: 1997,
      director: "罗伯托·贝尼尼",
      genres: ["喜剧", "剧情", "爱情"],
      rating: 9.0,
      description: "在纳粹集中营里，一位犹太父亲用幽默和想象力保护他的儿子免受恐怖的现实。",
      keywords: ["二战", "犹太人", "集中营", "父爱", "乐观"],
      countries: ["意大利"],
      cast: ["罗伯托·贝尼尼", "尼可莱塔·布拉斯基", "乔治·坎塔里尼"],
      searchTerms: "美丽人生 罗伯托·贝尼尼 喜剧 剧情 爱情 1997"
    },
    {
      id: 33,
      title: "机器人总动员",
      englishTitle: "WALL-E",
      year: 2008,
      director: "安德鲁·斯坦顿",
      genres: ["动画", "冒险", "家庭"],
      rating: 8.9,
      description: "在遥远的未来，一个孤独的垃圾清理机器人WALL-E爱上了一个名叫EVE的探测机器人，并跟随她进入太空。",
      keywords: ["机器人", "环保", "孤独", "爱情", "未来"],
      countries: ["美国"],
      cast: ["本·贝尔特", "艾丽莎·奈特", "杰夫·格尔林"],
      searchTerms: "机器人总动员 WALL-E 安德鲁·斯坦顿 动画 冒险 家庭 2008"
    },
    {
      id: 34,
      title: "飞屋环游记",
      englishTitle: "Up",
      year: 2009,
      director: "彼特·道格特, 鲍勃·彼德森",
      genres: ["动画", "冒险", "喜剧"],
      rating: 8.8,
      description: "一位年迈的鳏夫卡尔·弗雷德里克森用数千个气球将他的房子系起来，飞往南美洲，实现他与已故妻子的梦想。",
      keywords: ["冒险", "梦想", "老年", "友情", "飞屋"],
      countries: ["美国"],
      cast: ["爱德华·阿斯纳", "克里斯托弗·普卢默", "乔丹·长井"],
      searchTerms: "飞屋环游记 Up 彼特·道格特 鲍勃·彼德森 动画 冒险 喜剧 2009"
    },
    {
      id: 35,
      title: "三傻大闹宝莱坞",
      englishTitle: "3 Idiots",
      year: 2009,
      director: "拉库马·希拉尼",
      genres: ["喜剧", "剧情"],
      rating: 8.4,
      description: "两个朋友在寻找他们失踪的大学同学时，回忆起他们在印度一所顶尖工程学院的时光。",
      keywords: ["教育", "友情", "梦想", "压力", "印度"],
      countries: ["印度"],
      cast: ["阿米尔·汗", "卡琳娜·卡普尔", "马达范"],
      searchTerms: "三傻大闹宝莱坞 3 Idiots 拉库马·希拉尼 喜剧 剧情 2009"
    },
    {
      id: 36,
      title: "忠犬八公的故事",
      englishTitle: "Hachi: A Dog's Tale",
      year: 2009,
      director: "拉斯·霍尔斯道姆",
      genres: ["剧情", "家庭"],
      rating: 9.4,
      description: "一只名叫八公的秋田犬在主人去世后，每天都在火车站等待主人归来，持续了九年。",
      keywords: ["狗", "忠诚", "爱", "等待", "感人"],
      countries: ["美国", "英国"],
      cast: ["理查·基尔", "琼·艾伦", "萨拉·罗默尔"],
      searchTerms: "忠犬八公的故事 Hachi: A Dog's Tale 拉斯·霍尔斯道姆 剧情 家庭 2009"
    },
    {
      id: 37,
      title: "放牛班的春天",
      englishTitle: "The Chorus",
      year: 2004,
      director: "克里斯托夫·巴拉蒂",
      genres: ["剧情", "音乐"],
      rating: 9.3,
      description: "一位音乐老师在一所寄宿学校里，通过组建合唱团改变了孩子们的生活。",
      keywords: ["音乐", "教育", "希望", "救赎", "寄宿学校"],
      countries: ["法国", "瑞士", "德国"],
      cast: ["杰拉尔·朱诺", "弗朗索瓦·贝莱昂", "凯德·麦拉德"],
      searchTerms: "放牛班的春天 The Chorus 克里斯托夫·巴拉蒂 剧情 音乐 2004"
    },
      {
      id: 38,
      title: "当幸福来敲门",
      englishTitle: "The Pursuit of Happyness",
      year: 2006,
      director: "加布里尔·穆奇诺",
      genres: ["传记", "剧情"],
      rating: 9.1,
      description: "一个单亲爸爸为了给儿子一个更好的生活，努力奋斗成为一名股票经纪人。",
      keywords: ["父爱", "奋斗", "梦想", "贫困", "坚持"],
      countries: ["美国"],
      cast: ["威尔·史密斯", "贾登·史密斯", "桑迪·牛顿"],
      searchTerms: "当幸福来敲门 The Pursuit of Happyness 加布里尔·穆奇诺 传记 剧情 2006"
    },
      {
      id: 39,
      title: "十二怒汉",
      englishTitle: "12 Angry Men",
      year: 1957,
      director: "西德尼·吕美特",
      genres:["剧情","犯罪"],
      rating:9.4,
      description: "在一个谋杀案审判中，一个持不同意见的陪审员试图说服其他11个陪审员相信被告无罪。",
      keywords:["陪审团","正义","怀疑","法律","人性"],
      countries:["美国"],
      cast:["亨利·方达","李·科布","马丁·鲍尔萨姆"],
      searchTerms:"十二怒汉 12 Angry Men 西德尼·吕美特 剧情 犯罪 1957"
  
      },
      {
      id:40,
      title:"搏击俱乐部",
      englishTitle:"Fight Club",
      year:1999,
      director:"大卫·芬奇",
      genres:["剧情","惊悚","动作"],
      rating:8.8,
      description:"一个失眠的上班族和一个肥皂制造商组成了一个地下搏击俱乐部，并演变成更危险的东西。",
      keywords:["反社会","暴力","心理","身份","男性"],
      countries:["美国","德国"],
      cast:["爱德华·诺顿","布拉德·皮特","海伦娜·伯翰·卡特"],
      searchTerms: "搏击俱乐部 Fight Club 大卫·芬奇 剧情 惊悚 动作 1999"
      },
  
      {
          id: 41,
          title: "低俗小说",
          englishTitle: "Pulp Fiction",
          year: 1994,
          director: "昆汀·塔伦蒂诺",
          genres: ["犯罪", "剧情"],
          rating: 8.9,
          description: "几段暴力和救赎的故事交织在一起，讲述了洛杉矶黑帮、拳击手和一对小偷的故事。",
          keywords: ["犯罪", "暴力", "对话", "非线性叙事", "黑色幽默"],
          countries: ["美国"],
          cast: ["约翰·特拉沃尔塔", "乌玛·瑟曼", "塞缪尔·杰克逊"],
          searchTerms: "低俗小说 Pulp Fiction 昆汀·塔伦蒂诺 犯罪 剧情 1994"
      },
      {
          id: 42,
          title: "阿凡达",
          englishTitle: "Avatar",
          year: 2009,
          director: "詹姆斯·卡梅隆",
          genres: ["动作", "冒险", "科幻"],
          rating: 7.8,
          description: "在未来的潘多拉星球上，一名瘫痪的海军陆战队员被派往执行一项独特的任务，但却在保护当地土著居民纳美人和自身生存之间左右为难。",
          keywords: ["外星", "环保", "殖民", "战争", "特效"],
          countries: ["美国"],
          cast: ["萨姆·沃辛顿", "佐伊·索尔达娜", "西格妮·韦弗"],
          searchTerms: "阿凡达 Avatar 詹姆斯·卡梅隆 动作 冒险 科幻 2009"
  
      },
      {
          id:43,
          title:"盗火线",
          englishTitle:"Heat",
          year:1995,
          director:"迈克尔·曼",
          genres:["动作","犯罪","剧情"],
          rating:8.3,
          description:"一个资深警探和一个职业罪犯在洛杉矶展开了一场猫鼠游戏。",
          keywords:["警匪","对决","洛杉矶","抢劫","道德"],
          countries:["美国"],
          cast:["阿尔·帕西诺","罗伯特·德尼罗","方·基默"],
          searchTerms:"盗火线 Heat 迈克尔·曼 动作 犯罪 剧情 1995"
      },
      {
         id:44,
         title:"寄生虫",
         englishTitle:"Parasite",
         year:2019,
         director:"奉俊昊",
         genres:["剧情","惊悚","喜剧"],
         rating:8.5,
         description:"一个贫困的家庭逐渐渗透到一个富裕家庭的生活中，导致意想不到的后果。",
         keywords:["阶级","社会","韩国","悬疑","黑色幽默"],
         countries:["韩国"],
         cast:["宋康昊","崔宇植","朴素丹"],
         searchTerms:"寄生虫 Parasite 奉俊昊 剧情 惊悚 喜剧 2019"
      },
  
      {
        id:45,
        title:"看不见的客人",
        englishTitle:"The Invisible Guest",
        year:2016,
        director:"奥里奥尔·保罗",
        genres:["悬疑","惊悚","犯罪"],
        rating:8.1,
        description:"一位年轻的商人被指控谋杀，他与一位著名的律师合作，试图证明自己的清白。",
        keywords:["悬疑","反转","谋杀","真相","西班牙"],
        countries:["西班牙"],
        cast:["马里奥·卡萨斯","安娜·瓦格纳","何塞·科罗纳多"],
        searchTerms: "看不见的客人 The Invisible Guest 奥里奥尔·保罗 悬疑 惊悚 犯罪 2016"
  
      },
  
      {
          id:46,
          title: "绿皮书",
          englishTitle:"Green Book",
          year:2018,
          director:"彼得·法雷里",
          genres:["传记","喜剧","剧情"],
          rating:8.2,
          description: "1962年，一位著名的黑人钢琴家和他的白人司机兼保镖在美国南部进行巡回演出。",
          keywords:["种族歧视","友谊","公路","音乐","美国"],
          countries:["美国"],
          cast:["维果·莫腾森","马赫沙拉·阿里","琳达·卡德里尼"],
          searchTerms: "绿皮书 Green Book 彼得·法雷里 传记 喜剧 剧情 2018"
      },
      {
          id:47,
          title:"触不可及",
          englishTitle:"Intouchables",
          year:2011,
          director:"奥利维埃·纳卡什, 埃里克·托莱达诺",
          genres:["传记","喜剧","剧情"],
          rating:8.5,
          description:"一位富有的瘫痪贵族和他的非裔护理员之间产生了意想不到的友谊。",
          keywords:["友谊","残疾","阶级","法国","幽默"],
          countries:["法国"],
          cast:["弗朗索瓦·克鲁塞","奥马尔·希","安娜·勒尼"],
          searchTerms: "触不可及 Intouchables 奥利维埃·纳卡什 埃里克·托莱达诺 传记 喜剧 剧情 2011"
  
      },
       {
          id:48,
          title:"何以为家",
          englishTitle:"Capernaum",
          year:2018,
          director:"纳迪·拉巴基",
          genres:["剧情"],
          rating:8.4,
          description:"一个12岁的黎巴嫩男孩起诉他的父母，因为他们生下了他，却没有能力抚养他。",
          keywords:["贫困","儿童","黎巴嫩","社会","家庭"],
          countries:["黎巴嫩","法国"],
          cast:["赞恩·阿尔·拉菲亚","约丹诺斯·希费罗","博鲁瓦蒂夫·特雷杰·班科尔"],
          searchTerms:"何以为家 Capernaum 纳迪·拉巴基 剧情 2018"
       },
       {
          id:49,
          title: "星际迷航：暗黑无界",
          englishTitle: "Star Trek Into Darkness",
          year: 2013,
          director: "J·J·艾布拉姆斯",
          genres: ["动作", "冒险", "科幻"],
          rating: 7.7,
          description: "企业号船员被召回地球，却发现一股不可阻挡的恐怖势力从内部袭击了星际舰队，威胁着世界的未来。",
          keywords: ["太空", "科幻", "冒险", "星际舰队", "复仇"],
          countries: ["美国"],
          cast: ["克里斯·派恩", "扎克瑞·昆图", "本尼迪克特·康伯巴奇"],
          searchTerms: "星际迷航 暗黑无界 Star Trek Into Darkness J·J·艾布拉姆斯 动作 冒险 科幻 2013"
      },
      {
          id:50,
          title: "源代码",
          englishTitle:"Source Code",
          year:2011,
          director: "邓肯·琼斯",
          genres:["科幻", "惊悚", "动作"],
          rating:7.5,
          description: "一位士兵被派往过去，反复体验一起火车爆炸案的最后几分钟，以找出真凶。",
          keywords:["时间循环", "科幻", "悬疑", "火车", "恐怖袭击"],
          countries:["美国", "法国"],
          cast:["杰克·吉伦哈尔", "米歇尔·莫娜汉", "维拉·法米加"],
          searchTerms: "源代码 Source Code 邓肯·琼斯 科幻 惊悚 动作 2011"
      },
  
      {
          id:51,
          title: "禁闭岛",
          englishTitle: "Shutter Island",
          year: 2010,
          director: "马丁·斯科塞斯",
          genres: ["悬疑", "惊悚"],
          rating: 8.2,
          description: "1954年，两位联邦执法官前往一个精神病犯人岛屿调查一名失踪的病人。",
          keywords: ["精神病", "悬疑", "阴谋", "岛屿", "心理"],
          countries: ["美国"],
          cast: ["莱昂纳多·迪卡普里奥", "马克·鲁法洛", "本·金斯利"],
          searchTerms: "禁闭岛 Shutter Island 马丁·斯科塞斯 悬疑 惊悚 2010"
      },
  
       {
        id:52,
        title:"致命魔术",
        englishTitle:"The Prestige",
        year:2006,
        director:"克里斯托弗·诺兰",
        genres:["剧情","悬疑","科幻"],
        rating:8.5,
        description:"在20世纪初的伦敦，两位魔术师展开了一场激烈的竞争，最终导致悲剧。",
        keywords:["魔术","竞争","复仇","秘密","科学"],
        countries:["美国","英国"],
        cast:["克里斯蒂安·贝尔","休·杰克曼","斯嘉丽·约翰逊"],
        searchTerms: "致命魔术 The Prestige 克里斯托弗·诺兰 剧情 悬疑 科幻 2006"
  
       },
  
      {
          id: 53,
          title: "记忆碎片",
          englishTitle: "Memento",
          year: 2000,
          director: "克里斯托弗·诺兰",
          genres: ["悬疑", "惊悚"],
          rating: 8.4,
          description: "一个患有短期记忆丧失症的男人，利用纹身和宝丽来照片追查杀害他妻子的凶手。",
          keywords: ["记忆", "悬疑", "复仇", "非线性叙事", "失忆"],
          countries: ["美国"],
          cast: ["盖·皮尔斯", "凯瑞-安·莫斯", "乔·潘托里亚诺"],
          searchTerms: "记忆碎片 Memento 克里斯托弗·诺兰 悬疑 惊悚 2000"
      },
      {
         id:54,
         title:"莫娣",
         englishTitle:"Maudie",
         year:2016,
         director:"艾斯林·沃什",
         genres:["传记", "剧情","爱情"],
         rating:8.2,
         description:"加拿大民间艺术家莫娣·刘易斯克服了关节炎的痛苦，成为了一个受人喜爱的画家。",
         keywords:["艺术家","绘画","爱情","加拿大","残疾"],
         countries:["加拿大","爱尔兰"],
         cast:["莎莉·霍金斯","伊桑·霍克","卡瑞·玛切特"],
         searchTerms: "莫娣 Maudie 艾斯林·沃什 传记 剧情 爱情 2016"
      },
      {
        id:55,
        title:"海蒂和爷爷",
        englishTitle:"Heidi",
        year:2015,
        director:"阿兰·葛斯彭纳",
        genres:["剧情","家庭"],
        rating:8.7,
        description:"孤儿海蒂被送到阿尔卑斯山上与脾气古怪的爷爷一起生活，并在那里找到了真正的家。",
        keywords:["阿尔卑斯山","家庭","亲情","自然","瑞士"],
        countries:["瑞士","德国"],
        cast:["阿努克·斯特芬","布鲁诺·冈茨","昆林·艾格匹"],
        searchTerms: "海蒂和爷爷 Heidi 阿兰·葛斯彭纳 剧情 家庭 2015"
  
      },
      {
          id: 56,
          title: "小森林 夏秋篇",
          englishTitle: "Little Forest: Summer/Autumn",
          year: 2014,
          director: "森淳一",
          genres: ["剧情"],
          rating: 9.0,
          description: "一个年轻女子回到家乡小森，过着自给自足的生活，享受着大自然的馈赠。",
          keywords: ["乡村", "美食", "自然", "生活", "日本"],
          countries: ["日本"],
          cast: ["桥本爱", "三浦贵大", "松冈茉优"],
          searchTerms: "小森林 夏秋篇 Little Forest: Summer/Autumn 森淳一 剧情 2014"
      },
      {
        id:57,
        title: "小森林 冬春篇",
        englishTitle: "Little Forest: Winter/Spring",
        year:2015,
        director: "森淳一",
        genres:["剧情"],
        rating:9.0,
        description:"市子继续在小森过着自给自足的生活，并试图找到自己与母亲之间的关系。",
        keywords:["乡村","美食","自然","生活","日本"],
        countries:["日本"],
        cast:["桥本爱","三浦贵大","松冈茉优"],
        searchTerms: "小森林 冬春篇 Little Forest: Winter/Spring 森淳一 剧情 2015"
      },
      {
        id:58,
        title: "怦然心动",
        englishTitle: "Flipped",
        year:2010,
        director:"罗伯·莱纳",
        genres:["喜剧","剧情","爱情"],
        rating:9.1,
        description:"两个孩子从二年级开始就有了交集，他们对彼此的感情随着时间的推移而发生变化。",
        keywords:["初恋","爱情","成长","青春","美国"],
        countries:["美国"],
        cast:["玛德琳·卡罗尔","卡兰·麦克奥利菲","艾丹·奎因"],
        searchTerms: "怦然心动 Flipped 罗伯·莱纳 喜剧 剧情 爱情 2010"
      },
      {
          id:59,
          title: "爱在黎明破晓前",
          englishTitle:"Before Sunrise",
          year:1995,
          director: "理查德·林克莱特",
          genres:["剧情", "爱情"],
          rating:8.1,
          description:"一个美国男人和一个法国女人在火车上相遇，并在维也纳度过了一个浪漫的夜晚。",
          keywords:["爱情","旅行","对话","维也纳","缘分"],
          countries:["美国","奥地利","瑞士"],
          cast:["伊桑·霍克","朱莉·德尔佩"],
          searchTerms: "爱在黎明破晓前 Before Sunrise 理查德·林克莱特 剧情 爱情 1995"
  
      },
      {
         id:60,
         title:"爱在日落黄昏时",
         englishTitle:"Before Sunset",
         year:2004,
         director:"理查德·林克莱特",
         genres:["剧情","爱情"],
         rating:8.1,
         description:"九年后，杰西和席琳在巴黎重逢，并度过了一个下午。",
         keywords:["爱情","重逢","对话","巴黎","时间"],
         countries:["美国"],
         cast:["伊桑·霍克","朱莉·德尔佩"],
         searchTerms: "爱在日落黄昏时 Before Sunset 理查德·林克莱特 剧情 爱情 2004"
      },
      {
        id:61,
        title: "爱在午夜降临前",
        englishTitle:"Before Midnight",
        year: 2013,
        director: "理查德·林克莱特",
        genres:["剧情","爱情"],
        rating:7.9,
        description: "又过了九年，杰西和席琳在希腊度假，反思他们的关系和生活。",
        keywords:["爱情", "婚姻", "对话", "希腊","时间"],
        countries: ["美国"],
        cast:["伊桑·霍克", "朱莉·德尔佩"],
        searchTerms: "爱在午夜降临前 Before Midnight 理查德·林克莱特 剧情 爱情 2013"
  
      },
      {
          id:62,
          title: "布达佩斯大饭店",
          englishTitle: "The Grand Budapest Hotel",
          year:2014,
          director: "韦斯·安德森",
          genres: ["冒险","喜剧","剧情"],
          rating:8.1,
          description:"在20世纪30年代的欧洲，一位传奇酒店礼宾员和他年轻的门童卷入了一场盗窃案和家族遗产争夺战。",
          keywords: ["酒店","喜剧","欧洲","谋杀","艺术"],
          countries: ["美国","德国","英国"],
          cast: ["拉尔夫·费因斯","托尼·雷沃罗利","艾德里安·布洛迪"],
          searchTerms: "布达佩斯大饭店 The Grand Budapest Hotel 韦斯·安德森 冒险 喜剧 剧情 2014"
      },
  
      {
          id: 63,
          title: "天使爱美丽",
          englishTitle: "Amélie",
          year: 2001,
          director: "让-皮埃尔·热内",
          genres: ["喜剧", "爱情"],
          rating: 8.3,
          description: "一个巴黎女孩默默地帮助周围的人，并在这个过程中找到了自己的幸福。",
          keywords: ["巴黎", "善良", "爱情", "幻想", "法国"],
          countries: ["法国", "德国"],
          cast: ["奥黛丽·塔图", "马修·卡索维茨", "贾梅尔·德布兹"],
          searchTerms: "天使爱美丽 Amélie 让-皮埃尔·热内 喜剧 爱情 2001"
      },
      {
          id:64,
          title: "两杆大烟枪",
          englishTitle:"Lock, Stock and Two Smoking Barrels",
          year:1998,
          director: "盖·里奇",
          genres: ["喜剧","犯罪"],
          rating:8.2,
          description:"一群伦敦的朋友欠下了一笔巨额赌债，并卷入了一系列犯罪事件。",
          keywords: ["犯罪","喜剧","伦敦","黑帮","赌博"],
          countries: ["英国"],
          cast: ["杰森·弗莱明","德克斯特·弗莱彻","尼克·莫兰"],
          searchTerms: "两杆大烟枪 Lock, Stock and Two Smoking Barrels 盖·里奇 喜剧 犯罪 1998"
  
      },
      {
          id:65,
          title: "偷拐抢骗",
          englishTitle: "Snatch",
          year:2000,
          director: "盖·里奇",
          genres:["喜剧", "犯罪"],
          rating: 8.3,
          description:"伦敦的地下世界，一群各色人物为了争夺一颗钻石而展开混战。",
          keywords: ["犯罪", "喜剧", "伦敦", "黑帮", "钻石"],
          countries: ["英国", "美国"],
          cast:["本尼西奥·德尔·托罗", "丹尼斯·法里纳", "维尼·琼斯"],
          searchTerms: "偷拐抢骗 Snatch 盖·里奇 喜剧 犯罪 2000"
      },
  
      {
          id:66,
          title:"霸王别姬",
          englishTitle:"Farewell My Concubine",
          year:1993,
          director:"陈凯歌",
          genres:["剧情","爱情","音乐"],
          rating:9.6,
          description:"两位京剧演员在20世纪的中国经历了动荡的政治和社会变革。",
          keywords:["京剧","爱情","历史","中国","文化大革命"],
          countries:["中国","中国香港"],
          cast:["张国荣","张丰毅","巩俐"],
          searchTerms:"霸王别姬 Farewell My Concubine 陈凯歌 剧情 爱情 音乐 1993"
  
      },
       {
          id:67,
          title:"活着",
          englishTitle:"To Live",
          year:1994,
          director:"张艺谋",
          genres:["剧情","历史","战争"],
          rating:9.3,
          description:"一个中国家庭在20世纪经历了多次政治运动和苦难。",
          keywords:["家庭","历史","中国","生存","文化大革命"],
          countries:["中国","中国香港"],
          cast:["葛优","巩俐","姜武"],
          searchTerms:"活着 To Live 张艺谋 剧情 历史 战争 1994"
  
       },
       {
          id:68,
          title:"鬼子来了",
          englishTitle:"Devils on the Doorstep",
          year:2000,
          director:"姜文",
          genres:["剧情","战争","喜剧"],
          rating:9.3,
          description:"抗日战争期间，一个中国村庄的村民被迫照顾两名日本俘虏。",
          keywords:["抗日战争","战争","人性","黑色幽默","中国"],
          countries:["中国"],
          cast:["姜文","香川照之","姜宏波"],
          searchTerms: "鬼子来了 Devils on the Doorstep 姜文 剧情 战争 喜剧 2000"
       },
  
       {
        id:69,
        title: "阳光灿烂的日子",
        englishTitle: "In the Heat of the Sun",
        year:1994,
        director: "姜文",
        genres:["剧情", "青春"],
        rating:8.8,
        description: "文革时期，一群北京部队大院的孩子们度过了他们的青春岁月。",
        keywords:["文革","青春","成长","北京","友谊"],
        countries: ["中国", "中国香港"],
        cast:["夏雨", "宁静", "陶虹"],
        searchTerms: "阳光灿烂的日子 In the Heat of the Sun 姜文 剧情 青春 1994"
  
       },
        {
          id:70,
          title: "无人区",
          englishTitle:"No Man's Land",
          year:2013,
          director:"宁浩",
          genres:["剧情","犯罪","西部"],
          rating:8.2,
          description:"一个律师前往中国西北部的戈壁滩，卷入了一系列与盗猎者的冲突。",
          keywords:["西部","犯罪","人性","戈壁","中国"],
          countries:["中国"],
          cast:["徐峥","黄渤","余男"],
          searchTerms: "无人区 No Man's Land 宁浩 剧情 犯罪 西部 2013"
  
      },
      {
          id:71,
          title: "疯狂的石头",
          englishTitle: "Crazy Stone",
          year:2006,
          director:"宁浩",
          genres:["喜剧","犯罪"],
          rating:8.0,
          description: "重庆的一家工艺品厂发现了一块价值连城的翡翠，引来了各路人马的争夺。",
          keywords: ["喜剧","犯罪","重庆","翡翠","黑色幽默"],
          countries: ["中国", "中国香港"],
          cast:["郭涛","刘桦","黄渤"],
          searchTerms: "疯狂的石头 Crazy Stone 宁浩 喜剧 犯罪 2006"
      },
      {
        id:72,
        title:"心迷宫",
        englishTitle:"Coffin in the Mountain",
        year:2014,
        director:"忻钰坤",
        genres:["悬疑","剧情","犯罪"],
        rating:8.7,
        description:"一个中国乡村发生了一起命案，尸体在几个家庭之间辗转，揭示了人性的复杂。",
        keywords:["悬疑","乡村","人性","犯罪","中国"],
        countries:["中国"],
        cast:["霍卫民","王笑天","罗芸"],
        searchTerms: "心迷宫 Coffin in the Mountain 忻钰坤 悬疑 剧情 犯罪 2014"
  
      },
      {
        id:73,
        title:"暴裂无声",
        englishTitle:"Wrath of Silence",
        year:2017,
        director:"忻钰坤",
        genres:["犯罪","剧情","悬疑"],
        rating:8.2,
        description: "一个矿工在寻找失踪的儿子时，揭露了一个矿业公司的黑暗秘密。",
        keywords:["矿工","失踪","悬疑","犯罪","中国"],
        countries:["中国"],
        cast:["宋洋","姜武","袁文康"],
        searchTerms: "暴裂无声 Wrath of Silence 忻钰坤 犯罪 剧情 悬疑 2017"
      },
      {
        id:74,
        title: "哪吒之魔童降世",
        englishTitle:"Ne Zha",
        year:2019,
        director:"饺子",
        genres:["动画","奇幻","冒险"],
        rating:8.4,
        description:"哪吒本应是灵珠英雄，却成为了混世魔王，他将如何逆天改命，成为自己的英雄？",
        keywords:["哪吒","神话","命运","反抗","中国动画"],
        countries:["中国"],
        cast:["吕艳婷","囧森瑟夫","瀚墨"],
        searchTerms: "哪吒之魔童降世 Ne Zha 饺子 动画 奇幻 冒险 2019"
      },
        {
          id:75,
          title: "大圣归来",
          englishTitle: "Monkey King: Hero Is Back",
          year:2015,
          director:"田晓鹏",
          genres:["动画", "奇幻", "冒险"],
          rating: 8.3,
          description:"被压在五行山下五百年的孙悟空被一个小男孩解救，并踏上了自我救赎的旅程。",
          keywords:["孙悟空","西游记","冒险","救赎","中国动画"],
          countries: ["中国"],
          cast:["张磊", "林子杰", "吴文伦"],
          searchTerms: "大圣归来 Monkey King: Hero Is Back 田晓鹏 动画 奇幻 冒险 2015"
        },  {
            id: 76,
            title: "白日焰火",
            englishTitle: "Black Coal, Thin Ice",
            year: 2014,
            director: "刁亦男",
            genres: ["犯罪", "剧情", "悬疑"],
            rating: 7.4,
            description: "一名警察调查一系列发生在东北的碎尸案，并与一个神秘的女人产生了联系。",
            keywords: ["警察", "悬疑", "犯罪", "东北", "爱情"],
            countries: ["中国"],
            cast: ["廖凡", "桂纶镁", "王学兵"],
            searchTerms: "白日焰火 Black Coal, Thin Ice 刁亦男 犯罪 剧情 悬疑 2014"
          },
          {
            id: 77,
            title: "地球上的星星",
            englishTitle: "Like Stars on Earth",
            year: 2007,
            director: "阿米尔·汗",
            genres: ["剧情", "家庭"],
            rating: 8.4,
            description: "一个有阅读障碍的男孩，在他的美术老师的帮助下，找到了自信和自我价值。",
            keywords: ["阅读障碍", "教育", "儿童", "艺术", "印度"],
            countries: ["印度"],
            cast: ["达席尔·萨法瑞", "阿米尔·汗", "塔奈·切赫达"],
            searchTerms: "地球上的星星 Like Stars on Earth 阿米尔·汗 剧情 家庭 2007"
          },
          {
            id: 78,
            title: "摔跤吧！爸爸",
            englishTitle: "Dangal",
            year: 2016,
            director: "尼特什·提瓦瑞",
            genres: ["传记", "剧情", "运动"],
            rating: 8.4,
            description: "一位前摔跤手训练他的女儿们成为世界级摔跤冠军。",
            keywords: ["摔跤", "父女", "印度", "励志", "运动"],
            countries: ["印度"],
            cast: ["阿米尔·汗", "法缇玛·萨那·纱卡", "桑亚·玛荷塔"],
            searchTerms: "摔跤吧！爸爸 Dangal 尼特什·提瓦瑞 传记 剧情 运动 2016"
          },
            {
                id: 79,
                title: "神秘巨星",
                englishTitle: "Secret Superstar",
                year: 2017,
                director: "阿德瓦·香登",
                genres: ["剧情", "音乐"],
                rating: 7.8,
                description: "一个有才华的印度少女克服家庭阻力，追求自己的音乐梦想。",
                keywords: ["音乐", "梦想", "印度", "家庭", "励志"],
                countries: ["印度"],
                cast: ["泽伊拉·沃西姆", "阿米尔·汗", "梅·维贾"],
                searchTerms: "神秘巨星 Secret Superstar 阿德瓦·香登 剧情 音乐 2017"
            },
        
            {
                id: 80,
                title: "调音师",
                englishTitle: "Andhadhun",
                year: 2018,
                director: "斯里兰姆·拉格万",
                genres: ["犯罪", "惊悚", "喜剧"],
                rating: 8.2,
                description: "一个假装盲人的钢琴家意外卷入了一起谋杀案。",
                keywords: ["悬疑", "犯罪", "印度", "反转", "黑色幽默"],
                countries: ["印度"],
                cast: ["阿尤斯曼·库拉纳", "塔布", "拉迪卡·艾普特"],
                searchTerms: "调音师 Andhadhun 斯里兰姆·拉格万 犯罪 惊悚 喜剧 2018"
            },
        
            {
                id:81,
                title:"一个母亲的复仇",
                englishTitle:"Mom",
                year:2017,
                director:"拉维·德耶瓦尔",
                genres:["犯罪","剧情","惊悚"],
                rating:7.2,
                description:"一个继母为被强奸的女儿寻求正义。",
                keywords:["复仇","家庭","印度","正义","犯罪"],
                countries:["印度"],
                cast:["希里黛玉","阿克夏耶·坎纳","萨佳·阿里"],
                searchTerms:"一个母亲的复仇 Mom 拉维·德耶瓦尔 犯罪 剧情 惊悚 2017"
            },
          {
            id:82,
            title:"起跑线",
            englishTitle:"Hindi Medium",
            year:2017,
            director:"萨基特·乔杜里",
            genres:["喜剧","剧情"],
            rating:7.8,
            description:"一对印度夫妇为了让女儿进入一所好学校，想尽一切办法。",
            keywords:["教育","印度","社会","家庭","喜剧"],
            countries:["印度"],
            cast:["伊尔凡·可汗","萨巴·卡玛尔","内哈·迪胡皮阿"],
            searchTerms:"起跑线 Hindi Medium 萨基特·乔杜里 喜剧 剧情 2017"
        
          },
          {
            id:83,
            title:"无所不能",
            englishTitle: "Kaabil",
            year:2017,
            director:"桑杰·古普塔",
            genres:["动作","剧情","爱情"],
            rating:7.1,
            description:"一个盲人男子为他被强奸和杀害的妻子复仇。",
            keywords: ["复仇","爱情","盲人","印度","犯罪"],
            countries:["印度"],
            cast:["赫里尼克·罗斯汉","亚米·高塔姆","洛尼特·罗伊"],
            searchTerms: "无所不能 Kaabil 桑杰·古普塔 动作 剧情 爱情 2017"
          },
        
          {
            id:84,
            title: "误杀瞒天记",
            englishTitle:"Drishyam",
            year:2015,
            director:"尼西卡特·卡马特",
            genres:["犯罪","剧情","惊悚"],
            rating:8.2,
            description: "一个普通的男人为了保护家人，用电影中学到的知识与警察周旋。",
            keywords:["犯罪","家庭","印度","悬疑","警察"],
            countries:["印度"],
            cast:["阿贾耶·德乌干","塔布","施芮娅·萨兰"],
            searchTerms: "误杀瞒天记 Drishyam 尼西卡特·卡马特 犯罪 剧情 惊悚 2015"
          },
        
          {
              id:85,
              title:"误杀",
              englishTitle:"Sheep Without a Shepherd",
              year:2019,
              director:"柯汶利",
              genres:["犯罪","剧情","悬疑"],
              rating:7.6,
              description:"翻拍自《误杀瞒天记》，一个父亲利用电影知识保护家人。",
              keywords: ["犯罪","家庭","悬疑","翻拍","泰国"],
              countries:["中国"],
              cast:["肖央","谭卓","陈冲"],
              searchTerms: "误杀 Sheep Without a Shepherd 柯汶利 犯罪 剧情 悬疑 2019"
        
          },
            {
                id:86,
                title:"网络谜踪",
                englishTitle:"Searching",
                year:2018,
                director:"阿尼什·查甘蒂",
                genres:["悬疑","惊悚","剧情"],
                rating:7.6,
                description:"一位父亲通过女儿的笔记本电脑和社交媒体寻找失踪的女儿。",
                keywords:["失踪","网络","悬疑","社交媒体","家庭"],
                countries:["美国"],
                cast:["约翰·赵","黛博拉·梅辛","米歇尔·拉"],
                searchTerms:"网络谜踪 Searching 阿尼什·查甘蒂 悬疑 惊悚 剧情 2018"
            },
            {
                id:87,
                title:"恐怖直播",
                englishTitle:"The Terror Live",
                year:2013,
                director:"金秉祐",
                genres:["犯罪","惊悚","动作"],
                rating:7.7,
                description:"一位新闻主播接到恐怖分子的电话，并在直播中与恐怖分子对峙。",
                keywords:["恐怖袭击","直播","新闻","悬疑","韩国"],
                countries:["韩国"],
                cast:["河正宇","李璟荣","全慧珍"],
                searchTerms: "恐怖直播 The Terror Live 金秉祐 犯罪 惊悚 动作 2013"
            },
            {
                id: 88,
                title: "狩猎",
                englishTitle: "The Hunt",
                year: 2012,
                director: "托马斯·温特伯格",
                genres: ["剧情"],
                rating: 8.3,
                description: "一个男人被错误地指控性侵儿童，并成为小镇居民的攻击目标。",
                keywords: ["诬告", "社会", "儿童", "丹麦", "正义"],
                countries: ["丹麦"],
                cast: ["麦斯·米科尔森", "托玛斯·博·拉森", "安妮卡·韦德科普"],
                searchTerms: "狩猎 The Hunt 托马斯·温特伯格 剧情 2012"
            },
              {
                id: 89,
                title: "七号房的礼物",
                englishTitle: "Miracle in Cell No. 7",
                year: 2013,
                director: "李焕庆",
                genres: ["剧情", "喜剧", "家庭"],
                rating: 8.2,
                description: "一个智障父亲被错误地指控谋杀，并与狱友们建立了深厚的友谊。",
                keywords: ["监狱", "父女", "韩国", "感人", "冤案"],
                countries: ["韩国"],
                cast: ["柳承龙", "朴信惠", "葛素媛"],
                searchTerms: "七号房的礼物 Miracle in Cell No. 7 李焕庆 剧情 喜剧 家庭 2013"
              },
              {
                id:90,
                title: "素媛",
                englishTitle: "Hope",
                year: 2013,
                director:"李濬益",
                genres: ["剧情"],
                rating:9.3,
                description:"一个年幼的女孩遭受了性侵犯，她和她的家人努力克服创伤。",
                keywords: ["性侵","儿童","家庭","韩国","创伤"],
                countries: ["韩国"],
                cast: ["薛景求","严智苑","李来"],
                searchTerms:"素媛 Hope 李濬益 剧情 2013"
              },
              {
                id:91,
                title:"熔炉",
                englishTitle: "Silenced",
                year:2011,
                director:"黄东赫",
                genres:["剧情"],
                rating:9.3,
                description:"根据真实事件改编，讲述了一所聋哑学校的教师和学生遭受性侵犯的故事。",
                keywords: ["性侵","聋哑人","学校","韩国","社会"],
                countries: ["韩国"],
                cast:["孔侑","郑有美","金贤秀"],
                searchTerms:"熔炉 Silenced 黄东赫 剧情 2011"
        
              },
        
              {
                id:92,
                title:"辩护人",
                englishTitle:"The Attorney",
                year:2013,
                director:"杨宇锡",
                genres:["剧情"],
                rating:9.2,
                description:"根据真实事件改编，讲述了一位税务律师为被诬陷的学生辩护的故事。",
                keywords: ["律师","正义","韩国","政治","人权"],
                countries:["韩国"],
                cast:["宋康昊","金英爱","吴达洙"],
                searchTerms:"辩护人 The Attorney 杨宇锡 剧情 2013"
              },
               {
                id:93,
                title:"杀人回忆",
                englishTitle:"Memories of Murder",
                year:2003,
                director:"奉俊昊",
                genres:["犯罪","剧情","悬疑"],
                rating:8.1,
                description:"根据韩国华城连环杀人案改编，讲述了两位警探追查连环杀人犯的故事。",
                keywords: ["连环杀人案","警察","韩国","悬疑","真实事件"],
                countries:["韩国"],
                cast:["宋康昊","金相庆","金雷夏"],
                searchTerms:"杀人回忆 Memories of Murder 奉俊昊 犯罪 剧情 悬疑 2003"
        
               },
                {
                    id:94,
                    title:"老男孩",
                    englishTitle:"Oldboy",
                    year:2003,
                    director:"朴赞郁",
                    genres:["动作","剧情","悬疑"],
                    rating:8.4,
                    description:"一个男人被囚禁了15年，出狱后开始寻找真相和复仇。",
                    keywords: ["复仇","悬疑","暴力","韩国","禁锢"],
                    countries:["韩国"],
                    cast:["崔岷植","刘智泰","姜惠贞"],
                    searchTerms:"老男孩 Oldboy 朴赞郁 动作 剧情 悬疑 2003"
                },
            {
                id:95,
                title:"新世界",
                englishTitle:"New World",
                year:2013,
                director:"朴勋政",
                genres:["犯罪","剧情"],
                rating:7.6,
                description:"韩国最大犯罪集团的卧底警察在权力斗争中挣扎。",
                keywords:["卧底","黑帮","警察","韩国","犯罪"],
                countries:["韩国"],
                cast:["李政宰","崔岷植","黄政民"],
                searchTerms:"新世界 New World 朴勋政 犯罪 剧情 2013"
        
            },
            {
              id:96,
              title: "特工",
              englishTitle:"The Spy Gone North",
              year:2018,
              director:"尹钟彬",
              genres:["剧情","惊悚"],
              rating:7.2,
              description: "上世纪90年代，一名韩国间谍潜入朝鲜，调查核武器计划。",
              keywords:["间谍","朝鲜","韩国","政治","冷战"],
              countries:["韩国"],
              cast:["黄政民","李星民","赵震雄"],
              searchTerms:"特工 The Spy Gone North 尹钟彬 剧情 惊悚 2018"
        
            },
             {
                id:97,
                title:"燃烧",
                englishTitle:"Burning",
                year:2018,
                director:"李沧东",
                genres:["剧情","悬疑"],
                rating:7.5,
                description:"一个年轻男子在遇到一个神秘的女人后，卷入了一场失踪事件。",
                keywords:["悬疑","爱情","阶级","韩国","失踪"],
                countries:["韩国"],
                cast:["刘亚仁","史蒂文·元","全钟瑞"],
                searchTerms:"燃烧 Burning 李沧东 剧情 悬疑 2018"
             },
             {
              id:98,
              title: "小姐",
              englishTitle: "The Handmaiden",
              year: 2016,
              director: "朴赞郁",
              genres:["剧情", "爱情", "悬疑"],
              rating:8.1,
              description: "日据时期的朝鲜，一个女仆与一个继承巨额财产的女人之间的故事，充满阴谋和情欲。",
              keywords: ["阴谋", "爱情", "情欲", "朝鲜", "悬疑"],
              countries: ["韩国"],
              cast: ["金敏喜", "金泰梨", "河正宇"],
              searchTerms: "小姐 The Handmaiden 朴赞郁 剧情 爱情 悬疑 2016"
             },
             {
                id:99,
                title: "阳光姐妹淘",
                englishTitle:"Sunny",
                year: 2011,
                director:"姜炯哲",
                genres:["剧情", "喜剧"],
                rating:8.8,
                description:"一群中年妇女重聚，回忆她们高中时代的友谊。",
                keywords: ["友谊","青春","回忆","韩国","女性"],
                countries:["韩国"],
                cast:["沈恩京","姜素拉","闵孝琳"],
                searchTerms:"阳光姐妹淘 Sunny 姜炯哲 剧情 喜剧 2011"
             },
             {
              id: 100,
              title: "奇怪的她",
              englishTitle: "Miss Granny",
              year:2014,
              director:"黄东赫",
              genres:["喜剧","奇幻","家庭"],
              rating:7.7,
              description:"一位70多岁的老奶奶突然变回了20岁的模样。",
              keywords:["奇幻","喜剧","家庭","韩国","返老还童"],
              countries:["韩国"],
              cast:["沈恩京","罗文姬","朴仁焕"],
              searchTerms: "奇怪的她 Miss Granny 黄东赫 喜剧 奇幻 家庭 2014"
             },
             {
                id:101,
                title:"速度与激情5",
                englishTitle:"Fast Five",
                year:2011,
                director:"林诣彬",
                genres:["动作","犯罪","惊悚"],
                rating:7.3,
                description: "多米尼克·托雷托和他的团队在里约热内卢策划一场大型抢劫。",
                keywords: ["赛车","动作","犯罪","里约热内卢","团队"],
                countries: ["美国"],
                cast: ["范·迪塞尔","保罗·沃克","道恩·强森"],
                searchTerms: "速度与激情5 Fast Five 林诣彬 动作 犯罪 惊悚 2011"
        
             },
               {
                id:102,
                title:"速度与激情7",
                englishTitle:"Furious 7",
                year:2015,
                director:"温子仁",
                genres:["动作","犯罪","惊悚"],
                rating:7.1,
                description:"多米尼克·托雷托和他的团队面对一个为兄弟复仇的敌人。",
                keywords: ["赛车","动作","犯罪","复仇","团队"],
                countries: ["美国"],
                cast: ["范·迪塞尔","保罗·沃克","杰森·斯坦森"],
                searchTerms:"速度与激情7 Furious 7 温子仁 动作 犯罪 惊悚 2015"
               },
        
                {
                    id:103,
                    title:"碟中谍4",
                    englishTitle:"Mission: Impossible - Ghost Protocol",
                    year:2011,
                    director:"布拉德·伯德",
                    genres:["动作","冒险","惊悚"],
                    rating:7.4,
                    description:"伊森·亨特和他的团队被诬陷为恐怖分子，必须洗清自己的罪名。",
                    keywords: ["间谍","动作","特工","迪拜","高科技"],
                    countries:["美国"],
                    cast:["汤姆·克鲁斯","杰瑞米·雷纳","西蒙·佩吉"],
                    searchTerms: "碟中谍4 Mission: Impossible - Ghost Protocol 布拉德·伯德 动作 冒险 惊悚 2011"
                },
                {
                    id:104,
                    title:"碟中谍6：全面瓦解",
                    englishTitle:"Mission: Impossible - Fallout",
                    year:2018,
                    director:"克里斯托弗·麦奎里",
                    genres:["动作","冒险","惊悚"],
                    rating:7.7,
                    description:"伊森·亨特和他的团队必须阻止一场核武器危机。",
                    keywords:["间谍","动作","特工","核武器","危机"],
                    countries:["美国"],
                    cast:["汤姆·克鲁斯","亨利·卡维尔","文·瑞姆斯"],
                    searchTerms: "碟中谍6：全面瓦解 Mission: Impossible - Fallout 克里斯托弗·麦奎里 动作 冒险 惊悚 2018"
                },
            {
                id:105,
                title: "王牌特工：特工学院",
                englishTitle:"Kingsman: The Secret Service",
                year:2014,
                director: "马修·沃恩",
                genres:["动作", "冒险", "喜剧"],
                rating:7.7,
                description: "一个街头混混被招募进一个秘密特工组织，并接受训练。",
                keywords:["特工", "间谍", "英国", "喜剧", "绅士"],
                countries: ["英国", "美国"],
                cast: ["科林·费尔斯", "塔伦·埃格顿", "塞缪尔·杰克逊"],
                searchTerms: "王牌特工 特工学院 Kingsman: The Secret Service 马修·沃恩 动作 冒险 喜剧 2014"
            },
              {
                id:106,
                title: "王牌特工2：黄金圈",
                englishTitle:"Kingsman: The Golden Circle",
                year:2017,
                director: "马修·沃恩",
                genres:["动作","冒险","喜剧"],
                rating:6.7,
                description:"王牌特工总部被摧毁后，艾格西和梅林前往美国，与他们的美国同行合作。",
                keywords: ["特工","间谍","英国","美国","喜剧"],
                countries:["英国","美国"],
                cast:["塔伦·埃格顿","科林·费尔斯","马克·斯特朗"],
                searchTerms: "王牌特工2：黄金圈 Kingsman: The Golden Circle 马修·沃恩 动作 冒险 喜剧 2017"
              },
        
              {
                id:107,
                title:"007：大破天幕杀机",
                englishTitle:"Skyfall",
                year:2012,
                director:"萨姆·门德斯",
                genres:["动作","冒险","惊悚"],
                rating:7.8,
                description:"詹姆斯·邦德必须保护M女士，并追查一个与M女士过去有关的敌人。",
                keywords: ["詹姆斯·邦德","007","间谍","英国","动作"],
                countries:["英国","美国"],
                cast:["丹尼尔·克雷格","朱迪·丹奇","哈维尔·巴登"],
                searchTerms: "007：大破天幕杀机 Skyfall 萨姆·门德斯 动作 冒险 惊悚 2012"
              },
  ];

export default movies;